#!/usr/bin/env sh

# Set up Rails app. Run this script immediately after cloning the codebase.

install_dependencies() {
  bin/bundle install
  bower install
}

setup_database() {
  bin/rake db:setup
  bin/rake db:migrate
  bin/rake db:test:prepare
  bin/rake db:seed
  bin/rake db:migrate RAILS_ENV=test
}

install_dependencies
setup_database
