#!/usr/bin/env sh

# Set up Rails app. Run this script immediately after cloning the codebase.

ensure_qt_installed() {
  if !(which qmake > /dev/null); then
    if (which brew > /dev/null); then
      echo "Installing qt with Homebrew"
      brew update
      brew install qt
    else
      echo "Install qt (dependency of capybara-webkit) then run this script again"
      echo "Find help here: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit"
      exit 2
    fi
  fi
}

ensure_memcached_installed() {
  if !(which memcached > /dev/null); then
    if (which brew > /dev/null); then
      echo "Installing memcached with Homebrew"
      brew update
      brew install memcached
    else
      echo "Install memcached (dependency of Dalli) then run this script again"
      echo "Find help here: https://github.com/mperham/dalli"
      exit 2
    fi
  fi
}

ensure_postgres_installed() {
  if !(which psql > /dev/null); then
    echo "Install PostgreSQL then run this script again"
    exit 2
  fi
}

install_dependencies() {
  bin/bundle install
  bower install
}

setup_database() {
  bin/rake db:setup
  bin/rake db:migrate
  bin/rake db:test:prepare
  bin/rake db:seed
  bin/rake db:migrate RAILS_ENV=test
}

ensure_qt_installed
ensure_memcached_installed
ensure_postgres_installed
install_dependencies
setup_database
